[theme]
primaryColor = "#919e8b" # green
backgroundColor = "rgba(254, 248, 239, 1)"  # sepia yellow
secondaryBackgroundColor = "#ebd2b9" # wheat 
textColor = "#6e7075"   # gray
font = "sans serif"
[runner]
fastReruns = false
[server]
port = 8502