DB_USERNAME = "david"
DB_PASSWORD = "C0nnie97"
FERNET_KEY = "fC2eGa9S4aLXZgnkFyF2u-KVuHp4CjQjYxn7nci17vM="
OPENAI_API_KEY = "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"
MONGO_CONNECTION_STRING = "mongodb+srv://david:C0nnie97@bookshelf.ndy7bsv.mongodb.net/?retryWrites=true&w=majority&appName=bookshelf"
AWS_ACCESS_KEY_ID = "AKIA4N7SKOQHSHVHGR4L"
AWS_SECRET_ACCESS_KEY = "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"
ESRI_API_KEY = "AAPTxy8BH1VEsoebNVZXo8HurF89yH3U94of2tNjEtGqtHd_oOPwB6Hr-qkkjGSYglqlcPNZ0VCckRFM08AWdYsjNonYUEO27c0o5JX_sbSr8Uc6z49nfpUU9R9YXnwjObx6hGOpUhsJ6c_oa8bAS_fR3urXcvOj13NFnqaU9kwClmwOPV0FkyGImgJqG3DfUEMFESBYGB98_ttyyS6bNAv42iu5xggMftUElUE1kSZMaIs.AT1_5MNNtJR7-KZBGD1zaLOpJ8mFqcYsTj4iP-MoNd8DY0QK3a3rPFby9P6Hss_JYbKKc2MwLAm0uFr7YTX7tquTAdZE0xTsPHVSlHVbxzny8g_lJoh4kg9CTlx32HiatWjEmDYA8.AT1_5MNNtJR7"
SHIPENGINE_API_KEY = "TEST_ioChwePt81jYSvpcx+miyWf2Ubw9unDuMtEYUQgRAVo"

[azure]
# Get your Azure AI Language credentials from: https://portal.azure.com/
# Create a Language Service resource and get the key and endpoint
# Replace these placeholder values with your actual credentials
azure_language_key = "4pNETtbbESaQAErdspK5f7MNE8PVj8QjWHhXiQXTDYKrDpVXWUZmJQQJ99BHACYeBjFXJ3w3AAAaACOGbSDe"
azure_language_endpoint = "https://ellipsoid-ner.cognitiveservices.azure.com/"
